GENERAL:
  manual_seed: 123

DATA:
  dataset: ScanRefer
  num_points: 40000
  num_scenes: -1
  num_classes: 18
  use_augment: True

  # input
  use_height: True
  use_color: True
  use_normal: False
  use_multiview: False

MODEL:
  model: instancerefer

  # Filtering candidates
  use_gt_lang: True

  # Attribute Module
  attribute_module: attribute_module
  voxel_size_ap: 0.02

  # Relation Module
  relation_module: relation_module
  k: 8

  # Global Localization Module
  scene_module: scene_module
  voxel_size_glp: 0.05

  # Language Module
  language_module: lang_module
  use_bidir: True # bi-directional GRU

  # pretrain
  use_checkpoint:
  use_pretrained: False

TRAIN:
  batch_size: 64
  num_workers: 4
  epoch: 25

  lr: 0.001
  lr_decay_step: [15, 20]
  lr_decay_rate: 0.1
  bn_decay_step:
  bn_decay_rate:
  wd: 0.00001

  verbose: 20
  val_step: 2000
  start_val: 0




